// <auto-generated />
using System;
using Core.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.DAL.Migrations.Migrations
{
    [DbContext(typeof(CoreDBContext))]
    [Migration("20210402190518_UpdateGuild")]
    partial class UpdateGuild
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.DAL.Models.Guild.Guild", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("botbanroleid")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("guildid")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("muteroleid")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("novcroleid")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("usercount")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Core.DAL.Models.Infractions.Infraction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("guildid")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ownerid")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("id");

                    b.ToTable("Infractions");
                });

            modelBuilder.Entity("Core.DAL.Models.Quotes.Quote", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("owner")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("id");

                    b.ToTable("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
